create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null default 'member' check (role in ('admin', 'member')),
  active boolean not null default true,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_state (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.workspace_state enable row level security;
alter table public.audit_logs enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  assigned_role text;
begin
  select case when exists(select 1 from public.profiles) then 'member' else 'admin' end into assigned_role;
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'name', split_part(coalesce(new.email, 'کاربر'), '@', 1)),
    case when new.raw_app_meta_data->>'role' = 'admin' then 'admin' else assigned_role end
  )
  on conflict (id) do update set email = excluded.email, name = excluded.name, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();

drop policy if exists "profile self read" on public.profiles;
create policy "profile self read" on public.profiles for select to authenticated using (id = auth.uid());
drop policy if exists "profile self heartbeat" on public.profiles;

revoke all on public.workspace_state from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;

insert into public.workspace_state (id, data) values (
  'main',
  '{"tasks":[],"personalTasks":[],"notifications":[],"transactions":[],"clients":[],"leads":[],"contracts":[],"projects":[],"members":[],"chats":[],"letters":[],"attendance":[],"leaves":[],"logs":[],"events":[],"preferences":{"fontScale":1,"theme":"blue","labels":{"tasks":["سئو","فنی","طراحی","گزارش","عمومی"],"clients":["سئو سایت","طراحی سایت","پشتیبانی سایت","گرافیک","تولید محتوا"],"leads":["سئو سایت","طراحی سایت","کمپین تبلیغاتی","شبکه‌های اجتماعی"]}}}'::jsonb
) on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit)
values ('office-files', 'office-files', false, 20971520)
on conflict (id) do update set public = false, file_size_limit = 20971520;

drop policy if exists "authenticated office read own files" on storage.objects;
create policy "authenticated office read own files" on storage.objects for select to authenticated
using (bucket_id = 'office-files' and owner_id = auth.uid()::text);

drop policy if exists "authenticated office uploads" on storage.objects;
create policy "authenticated office uploads" on storage.objects for insert to authenticated
with check (bucket_id = 'office-files' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "authenticated office update own files" on storage.objects;
create policy "authenticated office update own files" on storage.objects for update to authenticated
using (bucket_id = 'office-files' and owner_id = auth.uid()::text);
drop policy if exists "authenticated office delete own files" on storage.objects;
create policy "authenticated office delete own files" on storage.objects for delete to authenticated
using (bucket_id = 'office-files' and owner_id = auth.uid()::text);
