create table if not exists public.workspace_backups (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.workspace_state(id) on delete cascade,
  data jsonb not null,
  saved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists workspace_backups_recent_idx
  on public.workspace_backups (workspace_id, created_at desc);

alter table public.workspace_backups enable row level security;
revoke all on public.workspace_backups from anon, authenticated;
